<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
    <ContentTargetFolders>.</ContentTargetFolders>
    <PackageId>NewsletterStudio.Plugins.UmbracoForms</PackageId>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://www.newsletterstudio.org</PackageProjectUrl>
    <PackageTags>umbraco umbraco-marketplace umbraco-forms newsletter-studio transactional</PackageTags>
    <Description>Plugin for Newsletter Studio to integrate with Umbraco Forms.</Description>
    <IncludeSymbols>false</IncludeSymbols>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <!-- Generate documentation -->
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <!-- PDBs beside DLLs -->
    <DebugType>portable</DebugType>
    <!-- Publish symbols as a separate .snupkg -->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <!-- Make SourceLink work + deterministic CI build -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <RepositoryUrl>https://github.com/enkelmedia/NewsletterStudio.Plugins.UmbracoForms</RepositoryUrl>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <Version>18.0.0</Version>
    <PackageVersion>18.0.0</PackageVersion>
    <InformationalVersion>18.0.0</InformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Web.Website" />
    <PackageReference Include="Umbraco.Cms.Api.Common" />
    <PackageReference Include="NewsletterStudio.Core" IncludeAssets="compile" />
    <PackageReference Include="NewsletterStudio.Web" IncludeAssets="compile" />
    <PackageReference Include="Umbraco.Forms.Core" />
    <PackageReference Include="Umbraco.Forms.Core.Providers" />
  </ItemGroup>
  <ItemGroup>
    <None Include="build\icon.png" Pack="true" PackagePath="\" />
    <None Include="build\readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="Client\**\*">
      <Pack>false</Pack>
    </Content>
  </ItemGroup>
  <Target Name="PreBuildClient_Debug" BeforeTargets="PreBuild" Condition="'$(Configuration)' == 'Debug'">
    <Message Text="Building (dev-mode), Client files in the ./Client-folder" Importance="High" />
    <!--<Exec Command="npm install" WorkingDirectory="$(ProjectDir)Client" />
    <Exec Command="npm run build:dev" WorkingDirectory="$(ProjectDir)Client" />-->
  </Target>
  <Target Name="PreBuildClient_Release" BeforeTargets="PreBuild" Condition="'$(Configuration)' == 'Release'">
    <Message Text="Building (release-mode), Client files in the ./Client-folder" Importance="High" />
    <Exec Command="npm install" WorkingDirectory="$(ProjectDir)Client" />
    <Exec Command="npm run build:dev" WorkingDirectory="$(ProjectDir)Client" />
  </Target>
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Message Text="Client side code was built. Mode: $(Configuration)" Importance="High" />
  </Target>
</Project>