// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetConfigurationResponse } from './types.gen';

export class UmbracoFormsResource {
    /**
     * @returns unknown OK
     * @throws ApiError
     */
    public static getConfiguration(): CancelablePromise<GetConfigurationResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/umbraco/management/api/newsletter-studio-umbraco-forms/get-configuration',
            errors: {
                401: 'The resource is protected and requires an authentication token'
            }
        });
    }
    
}