// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:54108/' | (string & {});
};

export type GetConfigurationResponse = {
    workspaces: Array<WorkspaceDefinitionFrontendModel>;
};

export type WorkspaceCustomFieldFrontendModel = {
    label: string;
    alias: string;
};

export type WorkspaceDefinitionFrontendModel = {
    key: string;
    name: string;
    customFields: Array<WorkspaceCustomFieldFrontendModel>;
};

export type GetConfigurationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/newsletter-studio-umbraco-forms/get-configuration';
};

export type GetConfigurationErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetConfigurationResponses = {
    /**
     * OK
     */
    200: GetConfigurationResponse;
};

export type GetConfigurationResponse2 = GetConfigurationResponses[keyof GetConfigurationResponses];
