// This file is auto-generated by @hey-api/openapi-ts

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type GetConfigurationResponseModel = {
    workspaces: Array<WorkspaceDefinitionFrontendModel>;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type WorkspaceCustomFieldFrontendModel = {
    label: string;
    alias: string;
};

export type WorkspaceDefinitionFrontendModel = {
    key: string;
    name: string;
    customFields: Array<WorkspaceCustomFieldFrontendModel>;
};

export type GetConfigurationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/newsletter-studio-umbraco-forms/get-configuration';
};

export type GetConfigurationErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetConfigurationResponses = {
    /**
     * OK
     */
    200: GetConfigurationResponseModel;
};

export type GetConfigurationResponse = GetConfigurationResponses[keyof GetConfigurationResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:54108' | (string & {});
};