// This file is auto-generated by @hey-api/openapi-ts

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export const EventMessageTypeModel = {
    DEFAULT: 'Default',
    INFO: 'Info',
    ERROR: 'Error',
    SUCCESS: 'Success',
    WARNING: 'Warning'
} as const;

export type GetConfigurationResponseModel = {
    workspaces: Array<(WorkspaceDefinitionFrontendModel)>;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type WorkspaceCustomFieldFrontendModel = {
    label: string;
    alias: string;
};

export type WorkspaceDefinitionFrontendModel = {
    key: string;
    name: string;
    customFields: Array<(WorkspaceCustomFieldFrontendModel)>;
};

export type GetConfigurationResponse = GetConfigurationResponseModel;

export type $OpenApiTs = {
    '/umbraco/management/api/newsletter-studio-umbraco-forms/get-configuration': {
        post: {
            res: {
                /**
                 * OK
                 */
                200: GetConfigurationResponseModel;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
};